### ISSUE TITLE
Error in the code from the example

### ISSUE THREAD

**Issue by StephanBroYT** [smpurkis/libre-linkup-py#1]
https://github.com/smpurkis/libre-linkup-py?tab=readme-ov-file#usage
```
Traceback (most recent call last):
  File "c:\Users\*****\OneDrive\Desktop\*****\file.py", line 14, in <module>
    client.login()
  File "C:\Users\*****\OneDrive\Desktop\******\lib\site-packages\libre_link_up\client.py", line 72, in login
    self.jwt_token = data["data"]["authTicket"]["token"]
KeyError: 'data'
```

**Comment by smpurkis** [comment]
Can you retry it with version 0.2.4, it should give a more indepth error message. Please remove any sensitive information from it first though, as it will include the full json response.

**Comment by StephanBroYT** [comment]
> Can you retry it with version 0.2.4, it should give a more indepth error message. Please remove any sensitive information from it first though, as it will include the full json response.

Traceback (most recent call last):
  File "c:\Users\***\OneDrive\Desktop\***\tst.py", line 26, in <module>
    client.login()
  File "C:\Users\***\OneDrive\Desktop\***\lib\site-packages\libre_link_up\client.py", line 70, in login
    response.raise_for_status()
  File "C:\Users\***\OneDrive\Desktop\***\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.libreview.io/llu/auth/login

**Comment by smpurkis** [comment]
Okay, that is a valid error from the libreview api and not related to this package. It is a general error and means that one of the inputs is incorrect. Likely either incorrect username or password.

It needs to be the username and password from the "LibreLinkUp" app namely, https://play.google.com/store/apps/details?id=org.nativescript.LibreLinkUp or the same on IOS. I don't know if this works using the freestyle app, https://play.google.com/store/apps/details?id=com.freestylelibre.app.gb

**Comment by StephanBroYT** [comment]
> Хорошо, это допустимая ошибка из libreview api и не связанная с этим пакетом. Это общая ошибка, которая означает, что один из входов неверен. Вероятно, неверное имя пользователя или пароль.
> 
> Это должны быть имя пользователя и пароль из приложения "LibreLinkUp", а именно, https://play.google.com/store/apps/details?id=org.nativescript.LibreLinkUp или то же самое на IOS. Я не знаю, работает ли это с использованием приложения freestyle, https://play.google.com/store/apps/details?id=com.freestylelibre.app.gb

username is email?

**Comment by smpurkis** [comment]
> > Хорошо, это допустимая ошибка из libreview api и не связанная с этим пакетом. Это общая ошибка, которая означает, что один из входов неверен. Вероятно, неверное имя пользователя или пароль.
> > Это должны быть имя пользователя и пароль из приложения "LibreLinkUp", а именно, https://play.google.com/store/apps/details?id=org.nativescript.LibreLinkUp или то же самое на IOS. Я не знаю, работает ли это с использованием приложения freestyle, https://play.google.com/store/apps/details?id=com.freestylelibre.app.gb
> 
> username is email?

Yep, thats correct

**Comment by StephanBroYT** [comment]
I deleted and recreated the LibreLinkUP account and it still gives me the error

> > > Хорошо, это допустимая ошибка из libreview api и не связанная с этим пакетом. Это общая ошибка, которая означает, что один из входов неверен. Вероятно, неверное имя пользователя или пароль.
> > > Это должны быть имя пользователя и пароль из приложения "LibreLinkUp", а именно, https://play.google.com/store/apps/details?id=org.nativescript.LibreLinkUp или то же самое на IOS. Я не знаю, работает ли это с использованием приложения freestyle, https://play.google.com/store/apps/details?id=com.freestylelibre.app.gb
> > 
> > 
> > username is email?
> 
> Yep, thats correct

**Comment by StephanBroYT** [comment]
I need to replace url with url = ‘https://api.libreview.ru’ and everything will work, probably because I live in Russia and there is a different API system here.

**Comment by Carebear80** [comment]
python example.py
Traceback (most recent call last):
  File "/home/machine/test2.py", line 23, in <module>
    client.login()
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 75, in login
    self.jwt_token = login_response["data"]["authTicket"]["token"]
KeyError: 'authTicket'                       I have to be doing something stupid.  I did check my usename and password it is the libre email and password right?  I'm not sure whats wrong with this...

**Comment by StephanBroYT** [comment]
> python example.py Traceback (most recent call last): File "/home/machine/test2.py", line 23, in client.login() File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 75, in login self.jwt_token = login_response["data"]["authTicket"]["token"] KeyError: 'authTicket' I have to be doing something stupid. I did check my usename and password it is the libre email and password right? I'm not sure whats wrong with this...

Try outputting login_response, ```print(login_response)```

**Comment by Carebear80** [comment]
I couldn't find a login_response parameter in client the closest thing I found was client.login which is the same as what I printed yesterday.  I did print several client methods though:
python                                                                                                                           
`Python 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0] on linux                                                                   
Type "help", "copyright", "credits" or "license" for more information.                                                              
>>> from libre_link_up import LibreLinkUpClient                                                                                     
>>> import os                                                                                                                       
>>> import dotenv                                                                                                                   
>>> import json                                                                                                                     
>>> dotenv.load_dotenv()                                                                                                            
False                                                                                                                               
>>>                                                                                                                                 
>>> client = LibreLinkUpClient(                                                                                                     
...     username=os.environ["LIBRE_LINK_UP_USERNAME"],                                                                              
...     password=os.environ["LIBRE_LINK_UP_PASSWORD"],                                                                              
...     url=os.environ["LIBRE_LINK_UP_URL"],                                                                                        
...     version="4.7.0",                                                                                                            
... )                                                                                                                               
>>> client.login()                                                                                                                  
Traceback (most recent call last):                                                                                                  
  File "<stdin>", line 1, in <module>                                                                                               
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 75, in login                    
    self.jwt_token = login_response["data"]["authTicket"]["token"]                                                                  
KeyError: 'authTicket'                                                                                                              
>>> client.
client.connection                  client.get_logbook_readings()      client.login()
client.country                     client.get_raw_connection(         client.password
client.get_connection(             client.get_raw_graph_readings()    client.url
client.get_connections()           client.get_raw_logbook_readings()  client.username
client.get_graph_readings()        client.headers                     client.version
client.get_latest_reading()        client.jwt_token                   
>>> client.url
'https://api-eu2.libreview.io'
>>> client.version
'4.7.0'
>>> client.headers
{'product': 'llu.android', 'version': '4.7.0', 'accept-encoding': 'gzip', 'cache-control': 'no-cache', 'connection': 'Keep-Alive', 'content-type': 'application/json', 'user-agent': 'Mozilla/5.0 (Linux; Android 10; Pixel 3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.181 Mobile Safari/537.36'}
>>> client.jwt_token
>>> client.country
>>> client.connection
>>> client.connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 82, in connection
    self._connection = self.get_connection()
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 121, in get_connection
    raw_connection = self.get_raw_connection(index)
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 112, in get_raw_connection
    raw_connections: list[dict[str, Any]] = self.get_connections()["data"]
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/libre_link_up/client.py", line 100, in get_connections
    response.raise_for_status()
  File "/home/machine/anaconda3/envs/gm/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-eu2.libreview.io/llu/connections`


The LIBRE_LINK_UP_USERNAME and LIBRE_LINK_UP_PASSWORD relative to libreview.com

**Comment by Carebear80** [comment]
Oh oh oh I at least figured this problem out.  It's the same problem as the Russian but I needed the US website: 
https://api.libreview.io
